Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: aiohttp in /home/vedant/.local/lib/python3.13/site-packages (3.11.13)
Requirement already satisfied: asyncio in /home/vedant/.local/lib/python3.13/site-packages (3.4.3)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/vedant/.local/lib/python3.13/site-packages (from aiohttp) (1.18.3)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp) (3.7)
